#!/bin/bash
function testHelp() {
  ../driller --help                                         > ${stdout}
  status=$?
  assertEquals "exit status"    "0"                         "${status}"
  assertEquals "stdout"         "USAGE:"                    "$(head -n1 ${stdout})"
}

function testNoArg() {
  ../driller                                                > ${stdout}
  status=$?
  assertEquals "exit status"    "0"                         "${status}"
  assertEquals "stdout"         "USAGE:"                    "$(head -n1 ${stdout})"
}

function testNoOption() {
  ../driller /tmp/driller/1/                                > ${stdout}
  status=$?
  assertEquals "exit status"    "0"                         "${status}"
  assertEquals "stdout"         "/tmp/driller/1/"           "$(cat ${stdout})"
}

function testDebugFile() {
  ../driller --debug /tmp/driller/1/1/../1/file             > ${stdout}
  assertEquals "path_arg"       "/tmp/driller/1/1/../1/file" "$(grep ^PATH_ARG: ${stdout} | cut -d: -f2)"
  assertEquals "dir"            "/tmp/driller/1/1/"         "$(grep ^DIR: ${stdout} | cut -d: -f2)"
  assertEquals "file"           "file"                      "$(grep ^FILE: ${stdout} | cut -d: -f2)"
  assertEquals "flat_path"      "/tmp/driller/1/1/file"     "$(grep ^FLAT_PATH: ${stdout} | cut -d: -f2)"
}

function testDebugDir() {
  ../driller --debug /tmp/driller/1/1/../1                  > ${stdout}
  assertEquals "path_arg"       "/tmp/driller/1/1/../1"     "$(grep ^PATH_ARG: ${stdout} | cut -d: -f2)"
  assertEquals "dir"            "/tmp/driller/1/1/"         "$(grep ^DIR: ${stdout} | cut -d: -f2)"
  assertEquals "file"           ""                          "$(grep ^FILE: ${stdout} | cut -d: -f2)"
  assertEquals "flat_path"      "/tmp/driller/1/1/"         "$(grep ^FLAT_PATH: ${stdout} | cut -d: -f2)"
}

function testDebugNonDir() {
  ../driller --debug /tmp/driller/3/3/../1                  > ${stdout} 2> ${stderr}
  status=$?
  assertEquals "exit status"    "0"                         "${status}"
  assertEquals "stdout"         ""                          "$(cat ${stdout})"
  assertEquals "stderr"         ""                          "$(cat ${stderr})"
}

function testAbsoluteSimpleDir() {
  ../driller --absolute /tmp/driller/1                      > ${stdout}
  status=$?
  assertEquals "exit status"    "0"                         "${status}"
  assertEquals "stdout"         "/tmp/driller/1/"           "$(cat ${stdout})"
}

function testAbsoluteComplicatedDir() {
  ../driller --absolute /tmp/driller/1/1/../                > ${stdout}
  status=$?
  assertEquals "exit status"    "0"                         "${status}"
  assertEquals "stdout"         "/tmp/driller/1/"           "$(cat ${stdout})"
}

function testAbsoluteWeirdRoot1() {
  ../driller --absolute //..//                              > ${stdout}
  status=$?
  assertEquals "exit status"    "0"                         "${status}"
  assertEquals "stdout"         "/"                         "$(cat ${stdout})"
}

function testAbsoluteWeirdRoot2() {
  ../driller --absolute //////                              > ${stdout}
  status=$?
  assertEquals "exit status"    "0"                         "${status}"
  assertEquals "stdout"         "/"                         "$(cat ${stdout})"
}

function testAbsoluteWeirdRoot3() {
  ../driller --absolute /./..///                            > ${stdout}
  status=$?
  assertEquals "exit status"    "0"                         "${status}"
  assertEquals "stdout"         "/"                         "$(cat ${stdout})"
}

function testAbsoluteSimpleFile() {
  ../driller --absolute /tmp/driller/1/1/file               > ${stdout}
  status=$?
  assertEquals "exit status"    "0"                         "${status}"
  assertEquals "stdout"         "/tmp/driller/1/1/file"     "$(cat ${stdout})"
}

function testAbsoluteFileLooksLikeSwitch() {
  d=$(pwd)
  pushd /tmp/driller/5/ &> /dev/null
  ${d}/../driller --absolute -file                          > ${stdout} 2> ${stderr}
  popd &> /dev/null
  status=$?
  assertEquals "exit status"    "0"                         "${status}"
  assertEquals "stdout"         "/tmp/driller/5/-file"      "$(cat ${stdout})"
  assertEquals "stderr"         ""                          "$(cat ${stderr})"
}

function testAbsoluteFileLooksLikeHelp() {
  d=$(pwd)
  pushd /tmp/driller/5/ &> /dev/null
  ${d}/../driller --absolute -- --help                         > ${stdout} 2> ${stderr}
  popd &> /dev/null
  status=$?
  assertEquals "exit status"    "0"                         "${status}"
  assertEquals "stdout"         "/tmp/driller/5/--help"     "$(cat ${stdout})"
  assertEquals "stderr"         ""                          "$(cat ${stderr})"
}

function testAbsoluteDeviceFile() {
  ../driller --absolute /dev/null                           > ${stdout}
  status=$?
  assertEquals "exit status"    "0"                         "${status}"
  assertEquals "stdout"         "/dev/null"                 "$(cat ${stdout})"
}

function testAbsoluteLinkFile() {
  ../driller --absolute /tmp/driller/4/link                 > ${stdout}
  status=$?
  assertEquals "exit status"    "0"                         "${status}"
  assertEquals "stdout"         "/tmp/driller/4/link"       "$(cat ${stdout})"
}

function testAbsoluteSymlinkFile() {
  ../driller --absolute /tmp/driller/4/symlink              > ${stdout}
  status=$?
  assertEquals "exit status"    "0"                         "${status}"
  assertEquals "stdout"         "/tmp/driller/4/symlink"    "$(cat ${stdout})"
}

function testAbsoluteWildcardFileSingle() {
  ../driller --absolute /tmp/driller/4/fi*                  > ${stdout}
  status=$?
  assertEquals "exit status"    "0"                         "${status}"
  assertEquals "stdout"         "/tmp/driller/4/file"       "$(cat ${stdout})"
}

function testAbsoluteWildcardFileMulti() {
  ../driller --absolute /tmp/driller/4/*                    > ${stdout} 2> ${stderr}
  status=$?
  assertEquals "exit status"    "0"                         "${status}"
  assertEquals "stdout"         "/tmp/driller/4/file
/tmp/driller/4/link
/tmp/driller/4/symlink"                          "$(cat ${stdout})"
}

function testAbsoluteComplicatedFile() {
  ../driller --absolute /tmp/driller/1/../1/1/file          > ${stdout}
  status=$?
  assertEquals "exit status"    "0"                         "${status}"
  assertEquals "stdout"         "/tmp/driller/1/1/file"     "$(cat ${stdout})"
}

function testScmRootGitSimpleDir() {
  ../driller --scm /tmp/driller/2/1                    > ${stdout}
  status=$?
  assertEquals "exit status"    "0"                         "${status}"
  assertEquals "stdout"         "/tmp/driller/2/"           "$(cat ${stdout})"
}

function testScmRootGitSimpleFile() {
  ../driller --scm /tmp/driller/2/file                 > ${stdout}
  status=$?
  assertEquals "exit status"    "0"                         "${status}"
  assertEquals "stdout"         "/tmp/driller/2/"           "$(cat ${stdout})"
}

function testScmRootHgSimpleDir() {
  ../driller --scm /tmp/driller/3/1                    > ${stdout}
  status=$?
  assertEquals "exit status"    "0"                         "${status}"
  assertEquals "stdout"         "/tmp/driller/3/"           "$(cat ${stdout})"
}

function testScmRootHgSimpleFile() {
  ../driller --scm /tmp/driller/3/file                 > ${stdout} 2> ${stderr}
  status=$?
  assertEquals "exit status"    "0"                         "${status}"
  assertEquals "stdout"         "/tmp/driller/3/"           "$(cat ${stdout})"
  assertEquals "stderr"         ""                          "$(cat ${stderr})"
}

function testScmRootHitRoot() {
  ../driller --scm ${HOME}                             > ${stdout} 2> ${stderr}
  status=$?
  assertEquals "exit status"    "1"                         "${status}"
  assertEquals "stderr"         "Fatal: SCM dir not found"  "$(cat ${stderr})"
  assertEquals "stdout"         ""                          "$(cat ${stdout})"
}

function testDirnameSimple() {
  ../driller --dirname /tmp/driller/1/1/file                > ${stdout}
  status=$?
  assertEquals "exit status"    "0"                         "${status}"
  assertEquals "stdout"         "/tmp/driller/1/1/"         "$(cat ${stdout})"
}

function testDirnameRelative() {
  ../driller --dirname ./                                   > ${stdout}
  status=$?
  assertEquals "exit status"    "0"                         "${status}"
  assertEquals "stdout"         "${running_dir}/"           "$(cat ${stdout})"
}

function testBasenameSimple() {
  ../driller --basename /tmp/driller/1/1/file               > ${stdout}
  status=$?
  assertEquals "exit status"    "0"                         "${status}"
  assertEquals "stdout"         "file"                      "$(cat ${stdout})"
}

function testBasenameRelative() {
  ../driller --basename ./test                              > ${stdout}
  status=$?
  assertEquals "exit status"    "0"                         "${status}"
  assertEquals "stdout"         "test"                      "$(cat ${stdout})"
}

function testBasenameNoFile() {
  ../driller --basename /tmp/driller/1/1/                   > ${stdout} 2> ${stderr}
  status=$?
  assertEquals "exit status"    "1"                         "${status}"
  assertEquals "stdout"         ""                          "$(cat ${stdout})"
  assertEquals "stderr"         "Fatal: Path isn't to a file" "$(cat ${stderr})"
}

function testBasenameWildcardFileSingle() {
  ../driller --basename /tmp/driller/4/fi*                  > ${stdout}
  status=$?
  assertEquals "exit status"    "0"                         "${status}"
  assertEquals "stdout"         "file"                      "$(cat ${stdout})"
}

function testBasenameWildcardFileMulti() {
  ../driller --basename /tmp/driller/4/*                    > ${stdout} 2> ${stderr}
  status=$?
  assertEquals "exit status"    "0"                         "${status}"
  assertEquals "stdout"         "file
link
symlink"                          "$(cat ${stdout})"
}


function oneTimeSetUp() {
  running_dir=$(pwd)
  stdout="/tmp/driller/stdout"
  stderr="/tmp/driller/stderr"
  mkdir -p /tmp/driller/1/1
  touch    /tmp/driller/1/1/file
  mkdir -p /tmp/driller/2/1
  mkdir -p /tmp/driller/2/.git
  touch    /tmp/driller/2/file
  mkdir -p /tmp/driller/3/.hg
  mkdir -p /tmp/driller/3/1
  touch    /tmp/driller/3/file
  mkdir -p /tmp/driller/4/
  touch    /tmp/driller/4/file
  ln       /tmp/driller/4/file /tmp/driller/4/link
  mkdir -p /tmp/driller/5/
  touch    /tmp/driller/5/-file
  touch    /tmp/driller/5/--help
  ln -s    /dev/null /tmp/driller/4/symlink
}

function oneTimeTearDown() {
  rm -Rf /tmp/driller
}

function TearDown() {
  rm -Rf ${stdout} ${stderr}
}

# TODO: test that current directory works when it's not qualified.
# TODO: test symlink to a dir ends in slash
# TODO: test that symlink to a file does not end in a slash.

# load and run shUnit2
source ./shunit/src/shunit2

# vim: ai ts=2 sw=2 et sts=2 ft=sh
