#!/usr/bin/env bash
source $(dirname $0)/functions.inc

function testBasename() {
  __run --basename ${test_dir}/1/fi*
  assertEquals "one match"      "file"                      "$stdout"

  __run --basename ${test_dir}/1/*
  assertEquals "three matches"    "3"  "$(wc -w $stdout_file | awk '{print $1}')"
}

function testAbsolute() {
  __run --absolute ${test_dir}/1/fi*
  assertEquals "one match"      "${test_dir}/1/file"       "$stdout"

  __run --absolute ${test_dir}/1/*
  assertEquals "three matches"    "3"  "$(wc -w $stdout_file | awk '{print $1}')"
}

# load and run shUnit2
source $(dirname $0)/shunit/src/shunit2

# vim: ai ts=2 sw=2 et sts=2 ft=sh
