#!/bin/bash
source $(dirname $0)/functions.inc

function testTargetPathTypes() {
  __run --dereference ${test_dir}/3/absolute_symlink
  assertEquals "absolute"         "/dev/null"                 "$stdout"

  __run --dereference ${test_dir}/3/relative_symlink
  assertEquals "relative"         "${test_dir}/1/"           "$stdout"

  __run --dereference ${test_dir}/3/symlink_to_symlink
  assertEquals "symlink"          "/dev/null"                 "$stdout"
}

function testLinkLoop() {
  __run --dereference ${test_dir}/3/linkloop1
  assertEquals "error"            "Fatal: Symlink loop."      "$stderr"
  assertEquals "status"           "1"                         "$status"
}

function testFromOutsideLinkDirectory() {
  cd ${test_dir}/

  __run --dereference ./3/absolute_symlink
  assertEquals "absolute"         "/dev/null"                 "$stdout"

  __run --dereference ./3/relative_symlink
  assertEquals "relative"         "${test_dir}/1/"           "$stdout"
}

# load and run shUnit2
source $(dirname $0)/shunit/src/shunit2

# vim: ai ts=2 sw=2 et sts=2 ft=sh
