#!/usr/bin/env bash
source $(dirname $0)/functions.inc

function testSimplePaths() {
  __run --absolute ${test_dir}/1
  assertEquals "directory"                    "${test_dir}/1/"       "$stdout"

  __run --absolute ${test_dir}/1/file
  assertEquals "file"                         "${test_dir}/1/file"   "$stdout"

  __run --absolute /dev/null
  assertEquals "device"                       "/dev/null"             "$stdout"

  __run --absolute ${test_dir}/2/hardlink
  assertEquals "hardlink"                     "${test_dir}/2/hardlink" "$stdout"

  __run --absolute ${test_dir}/2/symlink
  assertEquals "symlink"                      "${test_dir}/2/symlink" "$stdout"

  __run --absolute ${test_dir}/2/symlink_to_dir
  assertEquals "symlink to directory"         "${test_dir}/2/symlink_to_dir" "$stdout"

  __run --absolute ${test_dir}/2/symlink_to_dir/
  assertEquals "symlink to directory with slash" "${test_dir}/2/symlink_to_dir" "$stdout"

  ${driller} --absolute ${test_dir}/1/a\ file\ with\ spaces > ${stdout_file}
  assertEquals "file with spaces"             "${test_dir}/1/a file with spaces" "$(cat $stdout_file)"

  pushd ${test_dir}/1/ &> /dev/null
  __run --absolute -file
  assertEquals "file that looks like switch"  "${test_dir}/1/-file"  "$stdout"

  __run --absolute -- --help
  assertEquals "file that looks like help"    "${test_dir}/1/--help" "$stdout"

  __run --absolute ~/.driller_tmpfile
  assertEquals "expand ~"                     "${HOME}/.driller_tmpfile" "$stdout"
}

function testWeirdPaths() {
  __run --absolute ${test_dir}/1/../
  assertEquals "test_dir/1/../"           "${test_dir}/"         "$stdout"

  __run --absolute ${test_dir}/2/../1/../
  assertEquals "test_dir/2/../1/../" "${test_dir}/"        "$stdout"

  __run --absolute //..//
  assertEquals "//..//"                         "/"                   "$stdout"

  __run --absolute //////
  assertEquals "//////"                         "/"                   "$stdout"

  __run --absolute /./..///
  assertEquals "/./..///"                       "/"                   "$stdout"
}

function testHomeSubstitution() {
  __run --absolute "~"
  assertEquals "~" "${HOME}/" "$stdout"

  __run --absolute "~${USER}"
  assertEquals "~${USER}" "${HOME}/" "$stdout"

  __run --absolute "~${USER}/"
  assertEquals "~${USER}/" "${HOME}/" "$stdout"

  __run --absolute "~${USER}/.driller_tmpdir/file"
  assertEquals "~${USER}/.driller_tmpdir/file" "${HOME}/.driller_tmpdir/file" "$stdout"
}

# load and run shUnit2
source $(dirname $0)/shunit/src/shunit2

# vim: ai ts=2 sw=2 et sts=2 ft=sh
