#!/usr/bin/env bash
source $(dirname $0)/functions.inc

function testScmGit() {
  __run --scm ${test_dir}/git
  assertEquals "root"                 "${test_dir}/git/"           "$stdout"

  __run --scm ${test_dir}/git/1
  assertEquals "directory"            "${test_dir}/git/"           "$stdout"

  __run --scm ${test_dir}/git/file
  assertEquals "file"                 "${test_dir}/git/"           "$stdout"

  __run --scm ${test_dir}/git/1/2/3/4/file
  assertEquals "deep file"            "${test_dir}/git/"           "$stdout"

  __run --scm ${test_dir}/git/symlink
  assertEquals "internal symlink"     "${test_dir}/git/"           "$stdout"

  __run --scm ${test_dir}/git_symlink
  assertEquals "external symlink"     "${test_dir}/git/"           "$stdout"

  __run --scm ${test_dir}/
  assertEquals "non-scm stdout"       ""                            "$stdout"
  assertEquals "non-scm stderr"       "Fatal: SCM dir not found"    "$stderr"
  assertEquals "non-scm exit status"  "1"                           "$status"
}

function testScmMercurial() {
  __run --scm ${test_dir}/hg
  assertEquals "root"                 "${test_dir}/hg/"           "$stdout"

  __run --scm ${test_dir}/hg/1
  assertEquals "directory"            "${test_dir}/hg/"           "$stdout"

  __run --scm ${test_dir}/hg/file
  assertEquals "file"                 "${test_dir}/hg/"           "$stdout"
}

# load and run shUnit2
source $(dirname $0)/shunit/src/shunit2

# vim: ai ts=2 sw=2 et sts=2 ft=sh
