#!/usr/bin/env bash
. functions.inc

function testSimplePaths() {
  __run --absolute /tmp/driller/1
  assertEquals "directory"                    "/tmp/driller/1/"       "$stdout"

  __run --absolute /tmp/driller/1/file
  assertEquals "file"                         "/tmp/driller/1/file"   "$stdout"

  __run --absolute /dev/null
  assertEquals "device"                       "/dev/null"             "$stdout"

  __run --absolute /tmp/driller/2/hardlink
  assertEquals "hardlink"                     "/tmp/driller/2/hardlink" "$stdout"

  __run --absolute /tmp/driller/2/symlink
  assertEquals "symlink"                      "/tmp/driller/2/symlink" "$stdout"

  ${driller} --absolute /tmp/driller/1/a\ file\ with\ spaces > ${stdout_file}
  assertEquals "file with spaces"             "/tmp/driller/1/a file with spaces" "$(cat $stdout_file)"

  pushd /tmp/driller/1/ &> /dev/null
  __run --absolute -file
  assertEquals "file that looks like switch"  "/tmp/driller/1/-file"  "$stdout"

  __run --absolute -- --help
  assertEquals "file that looks like help"    "/tmp/driller/1/--help" "$stdout"

  __run --absolute ~/.driller_tmpfile
  assertEquals "expand ~"                     "${HOME}/.driller_tmpfile" "$stdout"
}

function testWeirdPaths() {
  __run --absolute /tmp/driller/1/../
  assertEquals "/tmp/driller/1/../"           "/tmp/driller/"         "$stdout"

  __run --absolute /tmp/driller/../driller/1/../
  assertEquals "/tmp/driller/../driller/1/../" "/tmp/driller/"        "$stdout"

  __run --absolute //..//
  assertEquals "//..//"                         "/"                   "$stdout"

  __run --absolute //////
  assertEquals "//////"                         "/"                   "$stdout"

  __run --absolute /./..///
  assertEquals "/./..///"                       "/"                   "$stdout"
}

function oneTimeSetUp() {
  running_dir=$(pwd)
  driller="${running_dir}/../driller"
  stdout_file="/tmp/driller/stdout"
  stderr_file="/tmp/driller/stderr"

  mkdir -p /tmp/driller/1 /tmp/driller/2
  touch /tmp/driller/1/file
  touch "/tmp/driller/1/a file with spaces"
  touch "/tmp/driller/1/-file"
  touch "/tmp/driller/1/--help"
  pushd /tmp/driller/2 &> /dev/null
  ln -s ../1/file symlink
  ln ../1/file hardlink
  ln -s ../1/ symlink_to_dir
  popd &> /dev/null

  touch ${HOME}/.driller_tmpfile
}

# load and run shUnit2
source ./shunit/src/shunit2

# vim: ai ts=2 sw=2 et sts=2 ft=sh
