#!/usr/bin/env bash
source $(dirname $0)/functions.inc

function testSwitches() {
  __run --help
  assertEquals "help exit status"    "0"                         "$status"
  assertEquals "help stdout"         "USAGE:"                    "$(head -n1 ${stdout_file})"

  __run --version
  assertEquals "version stdout"         "0"                      "$(cat ${stdout_file} | grep -E '^v[0-9]+\.[0-9]\.[0-9]$' &> /dev/null; echo $?)"

  __run
  assertEquals "no_arguments exit status"    "0"                 "$status"
  assertEquals "no_arguments stdout"         "USAGE:"            "$(head -n1 ${stdout_file})"

  __run /tmp/driller/1/
  assertEquals "no_action exit status"    "0"                    "$status"
  assertEquals "no_action stdout"         "/tmp/driller/1/"      "$stdout"
}

function testDirname() {
  __run --dirname /tmp/driller/1/1/file
  assertEquals "absolute file"            "/tmp/driller/1/1/"         "$stdout"

  __run --dirname /tmp/driller/1/1/file\ with\ spaces
  assertEquals "absolute file with spaces" "/tmp/driller/1/1/"        "$stdout"

  __run --dirname /tmp/driller/1/1/
  assertEquals "absolute directory"       "/tmp/driller/1/1/"         "$stdout"
}

function testBasename() {
  __run --basename /tmp/driller/1/1/file
  assertEquals "absolute"         "file"                      "$stdout"

  ${driller} --basename /tmp/driller/1/1/file\ with\ spaces > ${stdout_file}
  assertEquals "absolute with spaces" "file with spaces"        "$(cat $stdout_file)"

  __run --basename ./test
  assertEquals "relative"         "test"                      "$stdout"
}

function testStdin() {
  echo "/dev/null" | ${driller} --dirname > ${stdout_file}
  assertEquals "dirname"         "/dev/"                      "$(cat $stdout_file)"

  echo "/dev/null" | ${driller} --basename > ${stdout_file}
  assertEquals "basename"         "null"                       "$(cat $stdout_file)"

  echo "~" | ${driller} --absolute > ${stdout_file}
  assertEquals "absolute"         "${HOME}/"                       "$(cat $stdout_file)"
}

function oneTimeSetUp() {
  pushd $(dirname $0) &> /dev/null
  running_dir=$(pwd)
  popd &> /dev/null
  driller="${running_dir}/../driller"
  stdout_file="/tmp/driller/stdout"
  stderr_file="/tmp/driller/stderr"
  mkdir -p /tmp/driller/1/1
  touch    /tmp/driller/1/1/file
  touch    "/tmp/driller/1/1/file with spaces"
}

# load and run shUnit2
source $(dirname $0)/shunit/src/shunit2

# vim: ai ts=2 sw=2 et sts=2 ft=sh
